name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security:
    name: Security check
    uses: ./.github/workflows/security.yml

  build:
    needs: security-check
    name: Build project
    uses: ./.github/workflows/build.yml
